from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('test/', views.test_view, name='test'),
    path('simple-login-test/', views.simple_login_test, name='simple_login_test'),
    path('minimal-test/', views.minimal_test, name='minimal_test'),
    path('categories/', views.category_list, name='category_list'),
    path('products/', views.all_products, name='all_products'),
    path('search/', views.search_products, name='search_products'),
    path('category/<int:category_id>/', views.product_list_by_category, name='product_list_by_category'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('payment-direct/', views.payment_direct, name='payment_direct'),
    path('cart/add/', views.add_to_cart, name='add_to_cart'),
    path('remove-from-cart/<str:cart_key>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<str:cart_key>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('order-confirmation/', views.order_confirmation, name='order_confirmation'),
    path('thawani-order-confirmation/', views.thawani_order_confirmation, name='thawani_order_confirmation'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add-product/', views.add_product, name='add_product'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('login/', views.login_view, name='login'),
    path('signup/', views.signup_view, name='signup'),
    path('logout/', views.logout_view, name='logout'),
    path('orders-database/', views.orders_database, name='orders_database'),
    path('order-history/', views.order_history, name='order_history'),
    path('update-order-status/<int:order_id>/', views.update_order_status, name='update_order_status'),
    
    # Thawani Pay URLs
    path('thawani/create-session/', views.thawani_create_session, name='thawani_create_session'),
    path('thawani/payment-direct/', views.thawani_payment_direct, name='thawani_payment_direct'),
    path('thawani/success/', views.thawani_success, name='thawani_success'),
    path('thawani/test-success/', views.test_thawani_success, name='test_thawani_success'),
    path('thawani/debug-session/', views.debug_thawani_session, name='debug_thawani_session'),
    path('debug-thawani/', views.debug_thawani_page, name='debug_thawani_page'),
    path('test-thawani-flow/', views.test_thawani_flow, name='test_thawani_flow'),
    path('simple-test/', views.simple_test_view, name='simple_test_view'),
    path('cart/clear/', views.clear_cart, name='clear_cart'),
    path('thawani/cancel/', views.thawani_cancel, name='thawani_cancel'),
    path('thawani/mock-success/', views.thawani_mock_success, name='thawani_mock_success'),
    path('thawani/webhook/', views.thawani_webhook, name='thawani_webhook'),
    
    # Saved information management
    path('save-address-info/', views.save_address_info, name='save_address_info'),
    path('save-payment-info/', views.save_payment_info, name='save_payment_info'),
    path('get-saved-info/', views.get_saved_info, name='get_saved_info'),
    path('get-address-details/<int:address_id>/', views.get_address_details, name='get_address_details'),
    path('get-payment-details/<int:payment_id>/', views.get_payment_details, name='get_payment_details'),
]
