# Generated by Django 5.1.4 on 2025-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about_product',
            field=models.TextField(blank=True, help_text='Detailed description about the product'),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(blank=True, default='In Stock', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='TechMart', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='key_features',
            field=models.TextField(blank=True, help_text='Enter key features separated by new lines'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter specifications in format: Label: Value (one per line)'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='1 Year', max_length=100),
        ),
    ]
