# Generated by Django 5.1.4 on 2025-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_product_about_product_product_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_emoji',
            field=models.CharField(blank=True, help_text='Custom emoji for this category (e.g., 📱, 🎧, ⌨️)', max_length=10),
        ),
    ]
