# Generated by Django 5.1.4 on 2025-07-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.IntegerField(blank=True, help_text='Product ID from the Product model', null=True),
        ),
    ]
